; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
upload_speed = 115200
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, default
upload_port = COM4
monitor_port = COM4
lib_deps = 
	adafruit/Adafruit GFX Library@^1.11.11
	adafruit/Adafruit SSD1306@^2.5.13
	knolleary/PubSubClient
	esp32-camera
	WiFi
	PubSubClient
	bblanchon/ArduinoJson@^7.3.0
	densaugeo/base64@^1.4.0
